/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.PC;
import Modelo.Pokemon;
import java.util.ArrayList;

/**
 *
 * @author ElPul
 */
public class VentanaPC extends javax.swing.JFrame {

    private PC pc;
    private Pokemon pokemonSeleccionado;
    private int cajaSeleccion;

    public VentanaPC(PC pc) {
        this.pokemonSeleccionado = null;
        this.pc = pc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        panelPC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        botonCajaAnterior = new javax.swing.JButton();
        botonCajaPosterior = new javax.swing.JButton();
        botonCambiarPosicion = new javax.swing.JButton();
        botonMoverAEquipo = new javax.swing.JButton();
        botonLiberar = new javax.swing.JButton();
        botonQuitarItem = new javax.swing.JButton();
        textoCaja = new javax.swing.JLabel();
        panelEquipo = new javax.swing.JPanel();
        panelMochial = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        panelPC.setForeground(new java.awt.Color(0, 0, 0));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        botonCajaAnterior.setText("Caja anterior");
        botonCajaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajaAnteriorActionPerformed(evt);
            }
        });

        botonCajaPosterior.setText("Caja posterior");
        botonCajaPosterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajaPosteriorActionPerformed(evt);
            }
        });

        botonCambiarPosicion.setText("Cambiar posicion");
        botonCambiarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPosicionActionPerformed(evt);
            }
        });

        botonMoverAEquipo.setText("Mover a equipo");
        botonMoverAEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMoverAEquipoActionPerformed(evt);
            }
        });

        botonLiberar.setText("Liberar");
        botonLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLiberarActionPerformed(evt);
            }
        });

        botonQuitarItem.setText("Quitar item");
        botonQuitarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPCLayout = new javax.swing.GroupLayout(panelPC);
        panelPC.setLayout(panelPCLayout);
        panelPCLayout.setHorizontalGroup(
            panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPCLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPCLayout.createSequentialGroup()
                        .addComponent(botonCajaAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(botonCajaPosterior))
                    .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(panelPCLayout.createSequentialGroup()
                            .addComponent(botonCambiarPosicion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonMoverAEquipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonLiberar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonQuitarItem))))
                .addGap(46, 46, 46))
        );
        panelPCLayout.setVerticalGroup(
            panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCajaPosterior)
                    .addComponent(botonCajaAnterior)
                    .addComponent(textoCaja))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCambiarPosicion)
                    .addComponent(botonMoverAEquipo)
                    .addComponent(botonLiberar)
                    .addComponent(botonQuitarItem))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabs.addTab("PC", panelPC);

        javax.swing.GroupLayout panelEquipoLayout = new javax.swing.GroupLayout(panelEquipo);
        panelEquipo.setLayout(panelEquipoLayout);
        panelEquipoLayout.setHorizontalGroup(
            panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        panelEquipoLayout.setVerticalGroup(
            panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        tabs.addTab("Equipo Pokemon", panelEquipo);

        javax.swing.GroupLayout panelMochialLayout = new javax.swing.GroupLayout(panelMochial);
        panelMochial.setLayout(panelMochialLayout);
        panelMochialLayout.setHorizontalGroup(
            panelMochialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        panelMochialLayout.setVerticalGroup(
            panelMochialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        tabs.addTab("Mochila", panelMochial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCajaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajaAnteriorActionPerformed
        if (this.cajaSeleccion > 0) {
            this.cajaSeleccion--;
        }
        actualizarLista();
        textoCaja.setText("Caja: " + (this.cajaSeleccion + 1));
    }//GEN-LAST:event_botonCajaAnteriorActionPerformed

    private void botonMoverAEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMoverAEquipoActionPerformed

    }//GEN-LAST:event_botonMoverAEquipoActionPerformed

    private void botonCajaPosteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajaPosteriorActionPerformed
        if (this.cajaSeleccion < this.pc.getCajas().size() - 1) {
            this.cajaSeleccion++;
        }
        actualizarLista();
        textoCaja.setText("Caja: " + (this.cajaSeleccion + 1));
    }//GEN-LAST:event_botonCajaPosteriorActionPerformed

    private void botonCambiarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarPosicionActionPerformed

    private void botonLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLiberarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLiberarActionPerformed

    private void botonQuitarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonQuitarItemActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged

    }//GEN-LAST:event_tabsStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.cajaSeleccion = 0;
        actualizarLista();
        textoCaja.setText("Caja: " + (this.cajaSeleccion + 1));
    }//GEN-LAST:event_formWindowActivated

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (!evt.getValueIsAdjusting()) {
            int index = jList1.getSelectedIndex();
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void actualizarLista() {
        ArrayList<Pokemon> pokemones = pc.getCajas().get(this.cajaSeleccion).getPokemones();
        String[] elementos = new String[30];
        for (int i = 0; i < 30; i++) {
            elementos[i] = (pokemones.get(i) != null) ? pokemones.get(i).toString() : "Espacio vacío";
        }
        jList1.setListData(elementos);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCajaAnterior;
    private javax.swing.JButton botonCajaPosterior;
    private javax.swing.JButton botonCambiarPosicion;
    private javax.swing.JButton botonLiberar;
    private javax.swing.JButton botonMoverAEquipo;
    private javax.swing.JButton botonQuitarItem;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelEquipo;
    private javax.swing.JPanel panelMochial;
    private javax.swing.JPanel panelPC;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JLabel textoCaja;
    // End of variables declaration//GEN-END:variables
}
